baseURL = 'https://Medilore.github.io'
DefaultContentLanguage = "ja"
languageCode = "ja"
title = 'frazzled-technology'
theme = "archie"
HasCJKLanguage = true
disableKinds = ["RSS"]
pygmentsCodeFences = true

[params]
DateForm = "2006-12-30"
mode = "dark"