baseURL = 'https://Medilore.github.io/frazzled-technology/'
DefaultContentLanguage = "ja"
languageCode = "ja"
title = 'frazzled-technology'
theme = "archie"
HasCJKLanguage = true
disableKinds = ["RSS"]
pygmentsCodeFences = true
Copyright = "frazzled-technology"

[params]
DateForm = "2006-12-30"
mode = "dark"