baseURL = 'https://Medilore.github.io/frazzled-technology/'
DefaultContentLanguage = "ja"
languageCode = "ja-jp"
title = 'frazzled-technology'
theme = "archie"
HasCJKLanguage = true
disableKinds = ["RSS"]
pygmentsCodeFences = false
Copyright = "frazzled-technology"

[params]
mode = "dark"
useCDN = false